// The structural component of the initiative's self-coupling, from first
// principles: when a stance is refuted, the reply comes from a FORCED
// subset, and in this model a smaller menu has an exact price — the
// counting-entropy term of eq. (2). The threat capacity lost per forcing
// exchange is T·(ln W_free − ln W_forced), which is an increment of
// effective Δμ generated by the existing polarization: i.e., a J. Since
// J_structure ∝ T, the structural criticality ratio J·b/2T = b·⟨ln ratio⟩/2
// is a DIMENSIONLESS CONSTANT OF CHESS, computable by counting.
//
// This probe measures the constraint bite from played games: at every
// in-check position, ln(pseudo-legal mobility) − ln(legal evasions), minus
// the same gap at quiet positions (the legality-correction baseline).
//
// Honest reading (validated 2026-07-02): bite ≈ 1.8–2.0 in BOTH corpora
// (structural quantities are regime-independent), implying J_structure ≈
// 2.8 at T = 1.5 — right on the fitted anti-Stockfish J of 2.3–3.0, and a
// structural ratio of 0.57–0.75. But self-play's fitted J sits BELOW the
// structural value, so T·⟨ln ratio⟩ is the RANDOM-DEFENSE REFERENCE, not a
// bound: skilled defenders select optionality-preserving evasions (below),
// punishing attackers select option-minimizing checks (above). The excess
// Ĵ − J_structure is the skill signal, zero-referenced by the rules.
//
//   node j_floor_probe.js
const path = require('path');
const E = require('./engine_current.js');

function probe(file, label) {
  const d = require(path.resolve(__dirname, 'results', file));
  const games = d.games || d.rungs.flatMap(r => r.games);
  const inC = [], outC = [];
  for (const gm of games) {
    const g = new E.Chess();
    for (const san of gm.line.concat(gm.moves)) {
      const legal = g.fast_moves().length;
      if (legal > 0) {
        const mc = g.fast_mob_counts();
        const wFree = g.fast_turn() === 'w' ? mc.mw : mc.mb;
        if (wFree > 0) {
          const r = Math.log(wFree) - Math.log(legal);
          (g.fast_in_check() ? inC : outC).push(r);
        }
      }
      if (!g.move(san)) break;
    }
  }
  const mean = a => a.reduce((s, x) => s + x, 0) / a.length;
  const bite = mean(inC) - mean(outC);
  console.log(`${label.padEnd(24)} check=${String(inC.length).padStart(5)} quiet=${String(outC.length).padStart(6)}  ` +
    `⟨lnW−lnLegal⟩ check=${mean(inC).toFixed(3)} quiet=${mean(outC).toFixed(3)}  bite=${bite.toFixed(3)}`);
  return bite;
}

const bites = [
  probe('vs_sf1500_measure.json', 'vs SF-1500 (measure)'),
  probe('cooling_scan.json',      'self-play cooling scan'),
];
const bite = bites.reduce((s, x) => s + x, 0) / bites.length;
console.log();
for (const b of [0.6, 0.7, 0.8])
  console.log(`structural criticality ratio  b·bite/2  (b=${b}):  ${(b * bite / 2).toFixed(2)}`);
console.log(`implied J_structure at T=1.5: ${(1.5 * bite).toFixed(2)} Q-units  (fitted anti-SF J: 2.3–3.0)`);
